name: juice_point
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  convex_bottom_bar: ^3.2.0
  firebase_auth: ^4.19.5
  firebase_core: ^2.31.0
  cloud_firestore: ^4.17.3
  firebase_messaging: ^14.9.2
  firebase_storage: ^11.7.5
  flutter_local_notifications: ^17.1.2
  google_sign_in: ^6.2.1
  multi_dropdown: ^2.1.4
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/
