// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9TmteQHhvPdUd6WvymxaP96E6MCCH3OY',
    appId: '1:43042954248:web:0ed36cbbc0fc8d202b45bd',
    messagingSenderId: '43042954248',
    projectId: 'juice-point-4d411',
    authDomain: 'juice-point-4d411.firebaseapp.com',
    storageBucket: 'juice-point-4d411.appspot.com',
    measurementId: 'G-HJ5Q84SR7C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdkZstgTkVui1nCPk13-omMD24gEVgqCQ',
    appId: '1:43042954248:android:f18c44bc589719792b45bd',
    messagingSenderId: '43042954248',
    projectId: 'juice-point-4d411',
    storageBucket: 'juice-point-4d411.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAe1Xy5IPSE2At535ix97s1G1r5_lRmwQE',
    appId: '1:43042954248:ios:abe9b03d79b52c032b45bd',
    messagingSenderId: '43042954248',
    projectId: 'juice-point-4d411',
    storageBucket: 'juice-point-4d411.appspot.com',
    iosClientId: '43042954248-p6gg0fka4ms5kldfc1vl044jc1bh6v1v.apps.googleusercontent.com',
    iosBundleId: 'com.example.juicePoint',
  );
}
